version: '3.7'

services:
  web:
    build: ./web    
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ../.env.dev
    depends_on:
      - "postgres"
    restart: always

  
  postgres:
    image: postgres:14.2-alpine
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  pgadmin:
    image: dpage/pgadmin4:latest
    user: root
    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ${DATA_PATH_HOST}/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres