version: '3.7'

services:
    web:
        build: ./web    
        command: gunicorn CIgen.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - ../:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ../.env.prod
        depends_on:
        - postgres

    postgres:
        image: postgres:12.0-alpine
        volumes:
            - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}