version: '3.7'

services:
    postgres:
        image: postgres:14.2-alpine
        volumes:
        - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data/
        environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}

    web:
        build: ./web    
        command: gunicorn CIgen.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - ../:/usr/src/app/
        expose:
            - 8000
        env_file:
            - ../.env.prod
        depends_on:
            - postgres

    nginx:
        build: ./nginx
        ports:
            - 8080:80
        volumes:
            - ../:/usr/src/app/
        depends_on:
            - web